export const Adjustloc = {
    Txn_processing : "//a[contains(.,'Transaction Processing')]",
    Txn_selectadj : "//a[contains(text(),'Adjustment')]",
    add_adjust : '.justify-content-right > :nth-child(2)',
    client_type : "(//div[@class='below']//div)[1]",
    business_client :"//span[text()='Business']",
    client_name :'#walletAccountName',
    client_select:'.list-option',
    Account_numer:"(//div[@class='below'])[2]",
    Account_number_select : "//span[text()='7110045189']",
    Txn_amount : "#amount",
    Adj_type :"//div[text()=' Adjustment Type ']",
    Adj_type_select:"//span[text()='Manual Credit Adjustment']",
    Txn_Remarks : ':nth-child(2) > :nth-child(3) > div.col-sm-12 > .dama-select-box-forminput',
    Txn_Remarks_select: ':nth-child(1) > .deselect-option',
    Remarks : '#remarks1',
    Internal_remarks : '#internalRemarks',
    Submit : '[type="submit"]',
    Ifram_select : "//button[text()='okay']",
    search : '.justify-content-left > .btn',
    Txn_id_select : ':nth-child(3) > .odd > [style="cursor: pointer;"] > .slider',
    Txn_id_search : '#adjustmentId',
    Search_submit : "button[type='submit']",
    Adj_approve : "//table[@id='DataTables_Table_2']/tbody[1]/tr[1]/td[16]/span[1]/a[1]",
    Approve_iframe : '#centralModalSuccess > .modal-dialog > .modal-content > .modal-footer > .btn-dark',
    frame_expand : '.pull-right > .fa',

    
      }